# Generated by Django 3.0.6 on 2020-05-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='title',
            field=models.CharField(default='Title', max_length=120),
        ),
    ]
