# Generated by Django 2.2 on 2020-06-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_auto_20200605_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
