# Generated by Django 2.2 on 2020-06-11 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0008_auto_20200610_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poems.Poem'),
        ),
    ]
