# Generated by Django 2.2 on 2020-06-11 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_poem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='poem_user', through='poems.PoemLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
