# Generated by Django 2.2 on 2020-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0010_auto_20200611_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
