# Generated by Django 2.2 on 2020-06-29 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0011_auto_20200611_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL),
        ),
    ]
