# Generated by Django 2.2.13 on 2020-08-30 05:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0012_auto_20200629_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poems.Poem'),
        ),
    ]
